#开发环境
spring:
  #    数据库连接配置
  #    jdbc:mysql://47.103.16.140:3306/my-blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
  #    root
  #    Abc123!_
  datasource:
    url: jdbc:mysql://47.103.16.140:3306/my-blog?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Abc123!_
  #    jpa 配置
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    hibernate:
      ddl-auto: update
      #      输出sql语句
    #  配置日志级别
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  mvc:
    static-path-pattern: /static/**
  messages:
    basename: i18n/messages
logging:
  level:
    rooot: info
    com.zhao.guang.xiao.top: debug
  file: log/blog-dev.log
server:
  port: 8887
